def get_cnx_company():
    return companies


companies = {
    "ACC.NS": "ACC Limited",
    "AUBANK.NS": "AU Small Finance Bank Limited",
    "AARTIIND.NS": "Aarti Industries Limited",
    "ABBOTINDIA.NS": "Abbott India Limited",
    "ADANIGAS.NS": "Adani Total Gas Limited",
    "ADANIPORTS.NS": "Adani Ports and Special Economic Zone Limited",
    "ADANIPOWER.NS": "Adani Power Limited",
    "ADANITRANS.NS": "Adani Transmission Limited",
    "ABCAPITAL.NS": "Aditya Birla Capital Limited",
    "ABFRL.NS": "Aditya Birla Fashion and Retail Limited",
    "AJANTPHARM.NS": "Ajanta Pharma Limited",
    "ALKEM.NS": "Alkem Laboratories Limited",
    "AMARAJABAT.NS": "Amara Raja Batteries Limited",
    "AMBUJACEM.NS": "Ambuja Cements Limited",
    "APOLLOHOSP.NS": "Apollo Hospitals Enterprise Limited",
    "APOLLOTYRE.NS": "Apollo Tyres Limited",
    "ASHOKLEY.NS": "Ashok Leyland Limited",
    "ASIANPAINT.NS": "Asian Paints Limited",
    "AUROPHARMA.NS": "Aurobindo Pharma Limited",
    "DMART.NS": "Avenue Supermarts Limited",
    "AXISBANK.NS": "Axis Bank Limited",
    "BAJAJ-AUTO.NS": "Bajaj Auto Limited",
    "BAJFINANCE.NS": "Bajaj Finance Limited",
    "BAJAJFINSV.NS": "Bajaj Finserv Limited",
    "BAJAJHLDNG.NS": "Bajaj Holdings and Investment Limited",
    "BALKRISIND.NS": "Balkrishna Industries Limited",
    "BANDHANBNK.NS": "Bandhan Bank Limited",
    "BANKBARODA.NS": "Bank of Baroda",
    "BANKINDIA.NS": "Bank of India",
    "BATAINDIA.NS": "Bata India Limited",
    "BERGEPAINT.NS": "Berger Paints India Limited",
    "BEL.NS": "Bharat Electronics Limited",
    "BHARATFORG.NS": "Bharat Forge Limited",
    "BHEL.NS": "Bharat Heavy Electricals Limited",
    "BPCL.NS": "Bharat Petroleum Corporation Limited",
    "BHARTIARTL.NS": "Bharti Airtel Limited",
    "INFRATEL.NS": "Bharti Infratel Limited",
    "BIOCON.NS": "Biocon Limited",
    "BBTC.NS": "Bombay Burmah Trading Corporation Limited",
    "BOSCHLTD.NS": "Bosch Limited",
    "BRITANNIA.NS": "Britannia Industries Limited",
    "CESC.NS": "CESC Limited",
    "CADILAHC.NS": "Cadila Healthcare Limited",
    "CANBK.NS": "Canara Bank",
    "CASTROLIND.NS": "Castrol India Limited",
    "CHOLAFIN.NS": "Cholamandalam Investment and Finance Company Limited",
    "CIPLA.NS": "Cipla Limited",
    "CUB.NS": "City Union Bank Limited",
    "COALINDIA.NS": "Coal India Limited",
    "COLPAL.NS": "Colgate-Palmolive (India) Limited",
    "CONCOR.NS": "Container Corporation of India Limited",
    "COROMANDEL.NS": "Coromandel International Limited",
    "CROMPTON.NS": "Crompton Greaves Consumer Electricals Limited",
    "CUMMINSIND.NS": "Cummins India Limited",
    "DLF.NS": "DLF Limited",
    "DABUR.NS": "Dabur India Limited",
    "DALBHARAT.NS": "Dalmia Bharat Limited",
    "DIVISLAB.NS": "Divi's Laboratories Limited",
    "LALPATHLAB.NS": "Dr. Lal PathLabs Limited",
    "DRREDDY.NS": "Dr. Reddy's Laboratories Limited",
    "EDELWEISS.NS": "Edelweiss Financial Services Limited",
    "EICHERMOT.NS": "Eicher Motors Limited",
    "EMAMILTD.NS": "Emami Limited",
    "ENDURANCE.NS": "Endurance Technologies Limited",
    "ESCORTS.NS": "Escorts Kubota Limited",
    "EXIDEIND.NS": "Exide Industries Limited",
    "FEDERALBNK.NS": "Federal Bank Limited",
    "FORTIS.NS": "Fortis Healthcare Limited",
    "FRETAIL.NS": "Future Retail Limited",
    "GAIL.NS": "GAIL (India) Limited",
    "GMRINFRA.NS": "GMR Infrastructure Limited",
    "GICRE.NS": "General Insurance Corporation of India",
    "GLENMARK.NS": "Glenmark Pharmaceuticals Limited",
    "GODREJAGRO.NS": "Godrej Agrovet Limited",
    "GODREJCP.NS": "Godrej Consumer Products Limited",
    "GODREJIND.NS": "Godrej Industries Limited",
    "GODREJPROP.NS": "Godrej Properties Limited",
    "GRASIM.NS": "Grasim Industries Limited",
    "GUJGASLTD.NS": "Gujarat Gas Limited",
    "GSPL.NS": "Gujarat State Petronet Limited",
    "HCLTECH.NS": "HCL Technologies Limited",
    "HDFCAMC.NS": "HDFC Asset Management Company Limited",
    "HDFCBANK.NS": "HDFC Bank Limited",
    "HDFCLIFE.NS": "HDFC Life Insurance Company Limited",
    "HAVELLS.NS": "Havells India Limited",
    "HEROMOTOCO.NS": "Hero MotoCorp Limited",
    "HEXAWARE.NS": "Hexaware Technologies Limited",
    "HINDALCO.NS": "Hindalco Industries Limited",
    "HINDPETRO.NS": "Hindustan Petroleum Corporation Limited",
    "HINDUNILVR.NS": "Hindustan Unilever Limited",
    "HINDZINC.NS": "Hindustan Zinc Limited",
    "HUDCO.NS": "Housing and Urban Development Corporation Limited",
    "HDFC.NS": "Housing Development Finance Corporation Limited",
    "ICICIBANK.NS": "ICICI Bank Limited",
    "ICICIGI.NS": "ICICI Lombard General Insurance Company Limited",
    "ICICIPRULI.NS": "ICICI Prudential Life Insurance Company Limited",
    "IDBI.NS": "IDBI Bank Limited",
    "IDFCFIRSTB.NS": "IDFC First Bank Limited",
    "ITC.NS": "ITC Limited",
    "IBULHSGFIN.NS": "Indiabulls Housing Finance Limited",
    "IBVENTURES.NS": "Indiabulls Ventures Limited",
    "INDHOTEL.NS": "The Indian Hotels Company Limited",
    "IOC.NS": "Indian Oil Corporation Limited",
    "IRCTC.NS": "Indian Railway Catering and Tourism Corporation Limited",
    "IGL.NS": "Indraprastha Gas Limited",
    "INDUSINDBK.NS": "IndusInd Bank Limited",
    "NAUKRI.NS": "Info Edge (India) Limited",
    "INFY.NS": "Infosys Limited",
    "INDIGO.NS": "InterGlobe Aviation Limited",
    "IPCALAB.NS": "IPCA Laboratories Limited",
    "JSWENERGY.NS": "JSW Energy Limited",
    "JSWSTEEL.NS": "JSW Steel Limited",
    "JINDALSTEL.NS": "Jindal Steel and Power Limited",
    "JUBLFOOD.NS": "Jubilant FoodWorks Limited",
    "JUBILANT.NS": "Jubilant Life Sciences Limited",
    "KOTAKBANK.NS": "Kotak Mahindra Bank Limited",
    "L&TFH.NS": "L&T Finance Holdings Limited",
    "LTTS.NS": "L&T Technology Services Limited",
    "LICHSGFIN.NS": "LIC Housing Finance Limited",
    "LTI.NS": "Larsen & Toubro Infotech Limited",
    "LT.NS": "Larsen & Toubro Limited",
    "LUPIN.NS": "Lupin Limited",
    "MRF.NS": "MRF Limited",
    "MGL.NS": "Mahanagar Gas Limited",
    "M&MFIN.NS": "Mahindra & Mahindra Financial Services Limited",
    "M&M.NS": "Mahindra & Mahindra Limited",
    "MANAPPURAM.NS": "Manappuram Finance Limited",
    "MRPL.NS": "Mangalore Refinery and Petrochemicals Limited",
    "MARICO.NS": "Marico Limited",
    "MARUTI.NS": "Maruti Suzuki India Limited",
    "MFSL.NS": "Max Financial Services Limited",
    "MINDTREE.NS": "Mindtree Limited",
    "MOTHERSUMI.NS": "Motherson Sumi Systems Limited",
    "MPHASIS.NS": "Mphasis Limited",
    "MUTHOOTFIN.NS": "Muthoot Finance Limited",
    "NATCOPHARM.NS": "Natco Pharma Limited",
    "NHPC.NS": "NHPC Limited",
    "NMDC.NS": "NMDC Limited",
    "NTPC.NS": "NTPC Limited",
    "NATIONALUM.NS": "National Aluminium Company Limited",
    "NESTLEIND.NS": "Nestle India Limited",
    "NAM-INDIA.NS": "Nippon Life India Asset Management Limited",
    "OBEROIRLTY.NS": "Oberoi Realty Limited",
    "ONGC.NS": "Oil and Natural Gas Corporation Limited",
    "OIL.NS": "Oil India Limited",
    "OFSS.NS": "Oracle Financial Services Software Limited",
    "PIIND.NS": "PI Industries Limited",
    "PNBHOUSING.NS": "PNB Housing Finance Limited",
    "PAGEIND.NS": "Page Industries Limited",
    "PETRONET.NS": "Petronet LNG Limited",
    "PFIZER.NS": "Pfizer Limited",
    "PIDILITIND.NS": "Pidilite Industries Limited",
    "PEL.NS": "Piramal Enterprises Limited",
    "POLYCAB.NS": "Polycab India Limited",
    "PFC.NS": "Power Finance Corporation Limited",
    "POWERGRID.NS": "Power Grid Corporation of India Limited",
    "PRESTIGE.NS": "Prestige Estates Projects Limited",
    "PGHH.NS": "Procter & Gamble Hygiene and Health Care Limited",
    "PNB.NS": "Punjab National Bank",
    "QUESS.NS": "Quess Corp Limited",
    "RBLBANK.NS": "RBL Bank Limited",
    "RECLTD.NS": "REC Limited",
    "RAJESHEXPO.NS": "Rajesh Exports Limited",
    "RELIANCE.NS": "Reliance Industries Limited",
    "SBICARD.NS": "SBI Cards and Payment Services Limited",
    "SBILIFE.NS": "SBI Life Insurance Company Limited",
    "SRF.NS": "SRF Limited",
    "SHREECEM.NS": "Shree Cement Limited",
    "SRTRANSFIN.NS": "Shriram Transport Finance Company Limited",
    "SIEMENS.NS": "Siemens Limited",
    "SBIN.NS": "State Bank of India",
    "SAIL.NS": "Steel Authority of India Limited",
    "SUNPHARMA.NS": "Sun Pharmaceutical Industries Limited",
    "SUNTV.NS": "Sun TV Network Limited",
    "SYNGENE.NS": "Syngene International Limited",
    "TVSMOTOR.NS": "TVS Motor Company Limited",
    "TCS.NS": "Tata Consultancy Services Limited",
    "TATACONSUM.NS": "Tata Consumer Products Limited",
    "TATAMOTORS.NS": "Tata Motors Limited",
    "TATAPOWER.NS": "Tata Power Company Limited",
    "TATASTEEL.NS": "Tata Steel Limited",
    "TECHM.NS": "Tech Mahindra Limited",
    "RAMCOCEM.NS": "The Ramco Cements Limited",
    "TITAN.NS": "Titan Company Limited",
    "TORNTPHARM.NS": "Torrent Pharmaceuticals Limited",
    "TORNTPOWER.NS": "Torrent Power Limited",
    "TRENT.NS": "Trent Limited",
    "UPL.NS": "UPL Limited",
    "ULTRACEMCO.NS": "UltraTech Cement Limited",
    "UNIONBANK.NS": "Union Bank of India",
    "UBL.NS": "United Breweries Limited",
    "MCDOWELL-N.NS": "United Spirits Limited",
    "VGUARD.NS": "V-Guard Industries Limited",
    "VBL.NS": "Varun Beverages Limited",
    "IDEA.NS": "Vodafone Idea Limited",
    "VOLTAS.NS": "Voltas Limited",
    "WHIRLPOOL.NS": "Whirlpool of India Limited",
    "WIPRO.NS": "Wipro Limited",
    "ZEEL.NS": "Zee Entertainment Enterprises Limited"
}
